<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_recipes',
		'title' => 'Recipes',
		'fields' => array (
			array (
				'key' => 'field_575c58059ab19',
				'label' => 'Recipe Title',
				'name' => 'recipe_title',
				'type' => 'text',
				'instructions' => 'Enter the title of the recipe.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_575c624324f38',
				'label' => 'Course',
				'name' => 'course',
				'type' => 'text',
				'instructions' => 'Enter the course type (Main Course, Appetizer, Side, etc.). You can make up anything.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_575c628124f39',
				'label' => 'Cuisine',
				'name' => 'cuisine',
				'type' => 'text',
				'instructions' => 'Enter the type of cuisine (Mexican, Thai, American, etc.) You can make up anything.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_575c62a224f3a',
				'label' => 'Prep Time',
				'name' => 'prep_time',
				'type' => 'text',
				'instructions' => 'Enter how long it will take to prepare.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_575c62bb24f3b',
				'label' => 'Cook Time',
				'name' => 'cook_time',
				'type' => 'text',
				'instructions' => 'Enter how long it will take to cook.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_575c62cd24f3c',
				'label' => 'Servings',
				'name' => 'servings',
				'type' => 'text',
				'instructions' => 'How many servings does this recipe create?',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_575c581a9ab1a',
				'label' => 'Ingredients',
				'name' => 'recipe_ingredients',
				'type' => 'wysiwyg',
				'instructions' => 'Enter your ingredients as a bulleted list to take advantage of automatic styling.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_575c58349ab1b',
				'label' => 'Directions',
				'name' => 'recipe_directions',
				'type' => 'wysiwyg',
				'instructions' => 'Enter the directions for the recipe. You can format this any way you like.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'recipe',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


?>